version: "2"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: always
    command: "sh -c 'echo \"server_tokens off; client_max_body_size 512m;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  controller:
    container_name: controller
    image: kvoli/scalrio-controller:latest
    env_file:
      - controller.env
    ports:
      - "443:443"
      - "80:80"
    restart: always
    depends_on:
      - watchtower

  worker:
    container_name: worker
    image: kvoli/scalrio-worker:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - watchtower

