version: "2"
services:
  nginx-proxy:
    build: ./nginx-proxy
    command: "sh -c 'echo \"server_tokens off; client_max_body_size 512m;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./default_location:/etc/nginx/vhost.d/default_location"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    depends_on:
      - nginx-proxy

  controller:
    container_name: controller
    image: kvoli/scalrio-controller:latest
    env_file:
      - controller.env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - nginx-proxy
      - watchtower
      - letsencrypt
